spring:
  application:
    name: department-consumer
  devtools:
    restart:
      enabled: true

  datasource:
    username: root
    password: root
    url: jdbc:mysql://49.232.45.80:3306/employees?serverTimezone=UTC&characterEncoding=utf-8
#    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8
debug: false

dubbo:
  application:
    name: department-consumer
  protocol:
    name: dubbo
    prot: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  timeout: 5000